---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: heal-devops-app-web
  labels:
    app.kubernetes.io/name: heal-devops-app-web
spec:
  minReadySeconds: 5
  progressDeadlineSeconds: 60
  selector:
    matchLabels:
      app.kubernetes.io/name: heal-devops-app-web
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: heal-devops-app-web
    spec:
      serviceAccountName: heal-devops-app-web
      terminationGracePeriodSeconds: 60
      securityContext:
        fsGroup: 22430
      containers:
        - name: heal-devops-app-web
          lifecycle:
            preStop:
              exec:
                command:
                  - sleep
                  - "10"
          env: 
            - name: REDIS_URL
              value: redis://redis:6379
          securityContext:
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: false
            runAsNonRoot: true
            runAsUser: 22430
          image: "scientificpizza/heal-app-web-dev:0.1.0-01fb37b"
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 3
            timeoutSeconds: 3
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 3
            timeoutSeconds: 3
            periodSeconds: 3
          imagePullPolicy: Always