version: "3.9"

services:

  web:
    build:
      context: .
      dockerfile: web.Dockerfile
    depends_on:
      - 'redis'
    environment: 
      - REDIS_URL=redis://redis:6379
    image: scientificpizza/heal-app-web-dev:0.1.0-01fb37b
    ports:
      - '5000:5000'

  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/data'

  worker:
    build:
      context: .
      dockerfile: worker.Dockerfile
    depends_on:
      - 'redis'
    environment:
      - REDIS_URL=redis://redis:6379
    image: scientificpizza/heal-app-worker-dev:0.1.0-01fb37b

volumes:
  redis: