---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: heal-devops-app-worker
  labels:
    app.kubernetes.io/name: heal-devops-app-worker
spec:
  minReadySeconds: 5
  progressDeadlineSeconds: 60
  selector:
    matchLabels:
      app.kubernetes.io/name: heal-devops-app-worker
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: heal-devops-app-worker
    spec:
      serviceAccountName: heal-devops-app-worker
      terminationGracePeriodSeconds: 60
      securityContext:
        fsGroup: 22430
      containers:
        - name: heal-devops-app-worker
          lifecycle:
            preStop:
              exec:
                command:
                  - sleep
                  - "10"
          env: 
            - name: REDIS_URL
              value: redis://redis:6379
          securityContext:
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: false
            runAsNonRoot: true
            runAsUser: 22430
          image: "scientificpizza/heal-app-worker-dev:0.1.0-01fb37b"
          imagePullPolicy: Always